# Generated by Django 5.2.7 on 2026-02-03 14:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('street', models.CharField(blank=True, default='', max_length=200)),
                ('barangay', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('province', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_rider', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_stage', models.IntegerField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('warning_count', models.IntegerField(default=0)),
                ('last_warning_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedGiftProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoostFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoostPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration', models.IntegerField()),
                ('time_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoostPlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.TextField()),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterRefundRequest',
            fields=[
                ('counter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_by', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10)),
                ('counter_refund_method', models.CharField(max_length=50)),
                ('counter_refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('counter_refund_type', models.CharField(blank=True, choices=[('return', 'Return'), ('keep', 'Keep')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('dispute', 'Dispute')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity_type', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_minutes', models.IntegerField(blank=True, null=True)),
                ('actual_minutes', models.IntegerField(blank=True, null=True)),
                ('delivery_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_data', models.FileField(blank=True, null=True, upload_to='disputes/evidence/')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='filed', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipt/')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('upload_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('status', models.TextField()),
                ('condition', models.CharField(max_length=50)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('is_refundable', models.BooleanField(blank=True, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('weight_unit', models.CharField(blank=True, default='kg', max_length=10)),
                ('critical_stock', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('removal_reason', models.TextField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_data', models.FileField(upload_to='product/')),
                ('file_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('option_ids', models.JSONField(blank=True, null=True)),
                ('option_map', models.JSONField(blank=True, null=True)),
                ('sku_code', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('weight_unit', models.CharField(blank=True, default='g', max_length=10)),
                ('critical_trigger', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_refundable', models.BooleanField(default=False)),
                ('refund_days', models.PositiveIntegerField(default=0)),
                ('allow_swap', models.BooleanField(default=False)),
                ('swap_type', models.CharField(choices=[('direct_swap', 'Direct swap'), ('swap_plus_payment', 'Swap + payment')], default='direct_swap', max_length=30)),
                ('minimum_additional_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('maximum_additional_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('swap_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/skus/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('detailed_reason', models.TextField(blank=True, null=True)),
                ('buyer_preferred_refund_method', models.CharField(choices=[('wallet', 'E-wallet'), ('bank', 'Bank Transfer'), ('remittance', 'Remittance'), ('voucher', 'Store Voucher')], max_length=50)),
                ('refund_type', models.CharField(choices=[('return', 'Return Item'), ('keep', 'Keep Item')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('negotiation', 'Negotiation'), ('rejected', 'Rejected'), ('dispute', 'Dispute'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('final_refund_type', models.CharField(blank=True, max_length=50, null=True)),
                ('total_refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_refund_method', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundMedia',
            fields=[
                ('refundmedia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.FileField(upload_to='refunds/media/')),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('main_title', models.CharField(max_length=100)),
                ('section_title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('file_data', models.FileField(upload_to='refunds/proof/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRemittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('barangay', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('valid_id_type', models.CharField(max_length=50)),
                ('valid_id_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('report_type', models.CharField(choices=[('account', 'Account'), ('product', 'Product'), ('shop', 'Shop')], max_length=20)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment'), ('fake_account', 'Fake Account'), ('fraud', 'Fraud'), ('counterfeit', 'Counterfeit Items'), ('misleading', 'Misleading Information'), ('intellectual_property', 'Intellectual Property Violation'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(choices=[('warning', 'Warning Issued'), ('suspension', 'Account Suspension'), ('product_removal', 'Product Removed'), ('shop_suspension', 'Shop Suspended'), ('content_removal', 'Content Removed'), ('no_action', 'No Action Taken'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField(blank=True, help_text='Duration in days for temporary actions', null=True)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal comments are only visible to moderators/admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_data', models.FileField(upload_to='reports/')),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequestItem',
            fields=[
                ('return_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_method', models.CharField(max_length=100)),
                ('logistic_service', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('shipped', 'Shipped'), ('received', 'Received'), ('inspected', 'Inspected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('problem', 'Problem')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('return_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequestMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('file_data', models.FileField(upload_to='returns/media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=200)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Philippines', max_length=100)),
                ('building_name', models.CharField(blank=True, default='', max_length=200)),
                ('floor_number', models.CharField(blank=True, default='', max_length=50)),
                ('unit_number', models.CharField(blank=True, default='', max_length=50)),
                ('landmark', models.CharField(blank=True, default='', max_length=300)),
                ('instructions', models.TextField(blank=True, default='')),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_picture', models.ImageField(blank=True, null=True, upload_to='shop/picture/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('wallet', 'E-Wallet'), ('bank', 'Bank Account'), ('remittance', 'Remittance')], max_length=20)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('valid_id_type', models.CharField(blank=True, max_length=100, null=True)),
                ('valid_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('discount_type', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('maximum_usage', models.IntegerField(default=0)),
                ('valid_until', models.DateField()),
                ('added_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('product_limit', models.IntegerField(default=500)),
                ('current_product_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('moderator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('otp', models.CharField(max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_brand', models.CharField(blank=True, max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='riders/vehicles/')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='riders/licenses/')),
                ('verified', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('availability_status', models.CharField(choices=[('offline', 'Offline'), ('available', 'Available for Deliveries'), ('busy', 'Busy - On Delivery'), ('break', 'On Break'), ('unavailable', 'Temporarily Unavailable')], default='offline', max_length=20)),
                ('is_accepting_deliveries', models.BooleanField(default=False)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='api_user_usernam_edfd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='api_user_email_a7eefd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='api_user_created_f8e07b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_suspended', 'suspended_until'], name='api_user_is_susp_25ec79_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_customer', 'is_suspended'], name='api_user_is_cust_153cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_moderator', 'is_suspended'], name='api_user_is_mode_da5c58_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_rider', 'is_suspended'], name='api_user_is_ride_b8d150_idx'),
        ),
        migrations.AddField(
            model_name='appliedgift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='appliedgiftproduct',
            name='applied_gift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_products', to='api.appliedgift'),
        ),
        migrations.AddField(
            model_name='boostplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='boost',
            name='boost_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.boostplan'),
        ),
        migrations.AddField(
            model_name='boostplanfeature',
            name='boost_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.boostplan'),
        ),
        migrations.AddField(
            model_name='boostplanfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boostfeature'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cartitem'),
        ),
        migrations.AddField(
            model_name='counterrefundrequest',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_requests_made', to='api.user'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_disputes', to='api.user'),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='disputeevidence',
            name='dispute_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='api.disputerequest'),
        ),
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_products', to='api.category'),
        ),
        migrations.AddField(
            model_name='issues',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='customeractivity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='boost',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='appliedgiftproduct',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='appliedgift',
            name='gift_product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_promotions', to='api.product'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='accepted_categories',
            field=models.ManyToManyField(blank=True, related_name='accepted_for_sku_swaps', to='api.category'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='api.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='api.productsku'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to='api.user'),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_refunds', to='api.user'),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='refund_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='api.refund'),
        ),
        migrations.AddField(
            model_name='counterrefundrequest',
            name='refund_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_requests', to='api.refund'),
        ),
        migrations.AddField(
            model_name='refundbank',
            name='refund_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='api.refund'),
        ),
        migrations.AddField(
            model_name='refundmedia',
            name='refund_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.refund'),
        ),
        migrations.AddField(
            model_name='refundmedia',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='refundproof',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.refund'),
        ),
        migrations.AddField(
            model_name='refundproof',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_refund_proofs', to='api.user'),
        ),
        migrations.AddField(
            model_name='refundremittance',
            name='refund_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remittance', to='api.refund'),
        ),
        migrations.AddField(
            model_name='refundwallet',
            name='refund_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='api.refund'),
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_moderator',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_moderator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='api.user'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='api.user'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='api.product'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to='api.user'),
        ),
        migrations.AddField(
            model_name='reportaction',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='api.report'),
        ),
        migrations.AddField(
            model_name='reportaction',
            name='taken_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True, 'is_moderator': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_taken', to='api.user'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.report'),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='api.user'),
        ),
        migrations.AddField(
            model_name='reportmedia',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.report'),
        ),
        migrations.AddField(
            model_name='returnaddress',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_return_addresses', to='api.user'),
        ),
        migrations.AddField(
            model_name='returnaddress',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_address', to='api.refund'),
        ),
        migrations.AddField(
            model_name='returnaddress',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_return_addresses', to='api.user'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='refund_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='api.refund'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_returns', to='api.user'),
        ),
        migrations.AddField(
            model_name='returnrequestitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_returns', to='api.user'),
        ),
        migrations.AddField(
            model_name='returnrequestmedia',
            name='return_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.returnrequestitem'),
        ),
        migrations.AddField(
            model_name='returnrequestmedia',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.product'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='api.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.shippingaddress'),
        ),
        migrations.AddField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.shop'),
        ),
        migrations.AddField(
            model_name='returnaddress',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_addresses', to='api.shop'),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to='api.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.shop'),
        ),
        migrations.AddField(
            model_name='counterrefundrequest',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
        migrations.AddField(
            model_name='boost',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
        migrations.AddField(
            model_name='appliedgift',
            name='shop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_gifts', to='api.shop'),
        ),
        migrations.AddField(
            model_name='shopfollow',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='api.shop'),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='api.user'),
        ),
        migrations.AddField(
            model_name='variants',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AddField(
            model_name='variants',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
        migrations.AddField(
            model_name='variantoptions',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.variants'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to='api.user'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.voucher'),
        ),
        migrations.AddField(
            model_name='shopfollow',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_follows', to='api.customer'),
        ),
        migrations.AddField(
            model_name='shop',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_shops', to='api.customer'),
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.customer'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AddField(
            model_name='customeractivity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['current_product_count', 'product_limit'], name='api_custome_current_3ef6ee_idx'),
        ),
        migrations.AddField(
            model_name='boost',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AddIndex(
            model_name='moderator',
            index=models.Index(fields=['approval_status'], name='api_moderat_approva_4ff0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expired_at'], name='api_otp_expired_d1784b_idx'),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
        migrations.AddField(
            model_name='riderschedule',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rider'),
        ),
        migrations.AddField(
            model_name='rider',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_riders', to='api.user'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rider'),
        ),
        migrations.AddIndex(
            model_name='boostplan',
            index=models.Index(fields=['status', 'price'], name='api_boostpl_status_48931b_idx'),
        ),
        migrations.AddIndex(
            model_name='boostplan',
            index=models.Index(fields=['created_at'], name='api_boostpl_created_1640c7_idx'),
        ),
        migrations.AddIndex(
            model_name='boostplanfeature',
            index=models.Index(fields=['boost_plan'], name='api_boostpl_boost_p_d6dfff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boostplanfeature',
            unique_together={('boost_plan', 'feature')},
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['dispute_id'], name='api_dispute_dispute_f8306b_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['user', 'timestamp'], name='api_logs_user_id_2a15a5_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['timestamp'], name='api_logs_timesta_a73708_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='api_notific_user_id_537f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='api_notific_created_238c70_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='api_payment_order_i_e43f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'transaction_date'], name='api_payment_status_d3f8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_date'], name='api_payment_transac_230ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='issues',
            index=models.Index(fields=['product'], name='api_issues_product_1d10cb_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgiftproduct',
            index=models.Index(fields=['applied_gift_id'], name='api_applied_applied_b2bd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgiftproduct',
            index=models.Index(fields=['product_id'], name='api_applied_product_a6d556_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedgiftproduct',
            unique_together={('applied_gift_id', 'product_id')},
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product'], name='api_product_product_10420e_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['product', 'is_active'], name='api_product_product_d904a2_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['sku_code'], name='api_product_sku_cod_b2a56d_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['quantity', 'is_active'], name='api_product_quantit_06230d_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['price'], name='api_product_price_f5f979_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'is_ordered'], name='api_cartite_user_id_e55e97_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product', 'is_ordered'], name='api_cartite_product_6fc50f_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['sku', 'is_ordered'], name='api_cartite_sku_id_e60f89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'user', 'sku')},
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order_id', 'status'], name='api_refund_order_i_b2e7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['requested_by', 'status'], name='api_refund_request_503960_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'requested_at'], name='api_refund_status_cd8289_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_payment_status'], name='api_refund_refund__c6f6af_idx'),
        ),
        migrations.AddIndex(
            model_name='disputerequest',
            index=models.Index(fields=['refund_id', 'status'], name='api_dispute_refund__8dcbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='disputerequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='api_dispute_request_0a36a0_idx'),
        ),
        migrations.AddIndex(
            model_name='refundmedia',
            index=models.Index(fields=['refund_id'], name='api_refundm_refund__e9af6c_idx'),
        ),
        migrations.AddIndex(
            model_name='refundproof',
            index=models.Index(fields=['refund'], name='api_refundp_refund__f7df5a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['report', 'created_at'], name='api_reportc_report__f8298e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['user', 'created_at'], name='api_reportc_user_id_ad17ac_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmedia',
            index=models.Index(fields=['report'], name='api_reportm_report__789c65_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['refund_id', 'status'], name='api_returnr_refund__b14e92_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['status', 'return_deadline'], name='api_returnr_status_50d51e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestmedia',
            index=models.Index(fields=['return_id'], name='api_returnr_return__5cf0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default'], name='api_shippin_user_id_bb003b_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_active'], name='api_shippin_user_id_19c8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['city', 'province'], name='api_shippin_city_cf2f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='api_order_user_id_d6ac48_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='api_order_status_1d49fe_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['approval', 'status'], name='api_order_approva_8c1d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='api_order_created_7fb22c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_amount'], name='api_order_total_a_cf727a_idx'),
        ),
        migrations.AddIndex(
            model_name='returnaddress',
            index=models.Index(fields=['shop', 'seller'], name='api_returna_shop_id_fc2131_idx'),
        ),
        migrations.AddIndex(
            model_name='returnaddress',
            index=models.Index(fields=['refund'], name='api_returna_refund__df23e6_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='api_report_report__7e7523_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='api_report_status_2ddde8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_moderator', 'status'], name='api_report_assigne_7f3075_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_account', 'status'], name='api_report_reporte_e59198_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_product', 'status'], name='api_report_reporte_425512_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_shop', 'status'], name='api_report_reporte_241505_idx'),
        ),
        migrations.AddIndex(
            model_name='counterrefundrequest',
            index=models.Index(fields=['refund_id', 'status'], name='api_counter_refund__c3b264_idx'),
        ),
        migrations.AddIndex(
            model_name='counterrefundrequest',
            index=models.Index(fields=['seller_id', 'requested_at'], name='api_counter_seller__86d3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['shop', 'name'], name='api_categor_shop_id_1d1b14_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgift',
            index=models.Index(fields=['shop_id', 'is_active'], name='api_applied_shop_id_5e8fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgift',
            index=models.Index(fields=['is_active', 'end_time'], name='api_applied_is_acti_148dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='api_userpay_user_id_b934c2_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['method_type', 'user'], name='api_userpay_method__81c359_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product'], name='api_variant_product_386403_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoptions',
            index=models.Index(fields=['variant'], name='api_variant_variant_29fb50_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoptions',
            index=models.Index(fields=['created_at'], name='api_variant_created_97d8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code', 'is_active'], name='api_voucher_code_22be1d_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['shop', 'is_active', 'valid_until'], name='api_voucher_shop_id_fc7fba_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['valid_until', 'is_active'], name='api_voucher_valid_u_0d8ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['order'], name='api_checkou_order_i_15b998_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['created_at'], name='api_checkou_created_bfe441_idx'),
        ),
        migrations.AddIndex(
            model_name='shopfollow',
            index=models.Index(fields=['shop', 'followed_at'], name='api_shopfol_shop_id_c8a37c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopfollow',
            index=models.Index(fields=['customer', 'followed_at'], name='api_shopfol_custome_3cc2c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shopfollow',
            unique_together={('customer', 'shop')},
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['customer', 'verified'], name='api_shop_custome_6f4c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['verified', 'status'], name='api_shop_verifie_965ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name'], name='api_shop_name_819709_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['created_at'], name='api_shop_created_311fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_suspended', 'suspended_until'], name='api_shop_is_susp_df0674_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop', 'rating'], name='api_review_shop_id_c2d6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='api_review_product_3b36e6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', 'created_at'], name='api_review_custome_b847e6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='api_review_created_24e07e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'upload_status'], name='api_product_shop_id_f8f170_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['customer', 'upload_status'], name='api_product_custome_c66e70_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['upload_status', 'created_at'], name='api_product_upload__955fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'upload_status'], name='api_product_categor_a32a57_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='api_product_price_b6b1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='api_product_created_a91d70_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_removed', 'removed_at'], name='api_product_is_remo_e56dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['customer', 'product'], name='api_favorit_custome_8ff48b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('product', 'customer')},
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['customer', 'created_at'], name='api_custome_custome_1cd373_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['product', 'created_at'], name='api_custome_product_cfe32d_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['status', 'end_date'], name='api_boost_status_bbff66_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['product', 'status'], name='api_boost_product_716937_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['shop', 'status'], name='api_boost_shop_id_d24e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['start_date', 'end_date'], name='api_boost_start_d_d7debe_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['customer', 'score'], name='api_airecom_custome_ad1273_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['created_at'], name='api_airecom_created_b47ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['rider', 'start_date'], name='api_timeoff_rider_i_268d02_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['status', 'start_date'], name='api_timeoff_status_425afd_idx'),
        ),
        migrations.AddIndex(
            model_name='riderschedule',
            index=models.Index(fields=['rider', 'day_of_week'], name='api_ridersc_rider_i_78958a_idx'),
        ),
        migrations.AddIndex(
            model_name='riderschedule',
            index=models.Index(fields=['day_of_week', 'is_available'], name='api_ridersc_day_of__37f42b_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['verified', 'availability_status'], name='api_rider_verifie_ecd891_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['availability_status', 'is_accepting_deliveries'], name='api_rider_availab_eb0625_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['last_status_update'], name='api_rider_last_st_17f9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order', 'status'], name='api_deliver_order_i_e86cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['rider', 'status'], name='api_deliver_rider_i_a81014_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'scheduled_delivery_time'], name='api_deliver_status_48c0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['created_at'], name='api_deliver_created_5fe707_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivered_at'], name='api_deliver_deliver_afb191_idx'),
        ),
    ]
