# Generated by Django 5.2.7 on 2026-02-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='api.productsku'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'user', 'sku')},
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['customer', 'score'], name='api_airecom_custome_ad1273_idx'),
        ),
        migrations.AddIndex(
            model_name='airecommendation',
            index=models.Index(fields=['created_at'], name='api_airecom_created_b47ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgift',
            index=models.Index(fields=['shop_id', 'is_active'], name='api_applied_shop_id_5e8fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgift',
            index=models.Index(fields=['is_active', 'end_time'], name='api_applied_is_acti_148dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgiftproduct',
            index=models.Index(fields=['applied_gift_id'], name='api_applied_applied_b2bd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedgiftproduct',
            index=models.Index(fields=['product_id'], name='api_applied_product_a6d556_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['status', 'end_date'], name='api_boost_status_bbff66_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['product', 'status'], name='api_boost_product_716937_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['shop', 'status'], name='api_boost_shop_id_d24e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['start_date', 'end_date'], name='api_boost_start_d_d7debe_idx'),
        ),
        migrations.AddIndex(
            model_name='boostplan',
            index=models.Index(fields=['status', 'price'], name='api_boostpl_status_48931b_idx'),
        ),
        migrations.AddIndex(
            model_name='boostplan',
            index=models.Index(fields=['created_at'], name='api_boostpl_created_1640c7_idx'),
        ),
        migrations.AddIndex(
            model_name='boostplanfeature',
            index=models.Index(fields=['boost_plan'], name='api_boostpl_boost_p_d6dfff_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'is_ordered'], name='api_cartite_user_id_e55e97_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product', 'is_ordered'], name='api_cartite_product_6fc50f_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['sku', 'is_ordered'], name='api_cartite_sku_id_e60f89_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['shop', 'name'], name='api_categor_shop_id_1d1b14_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['order'], name='api_checkou_order_i_15b998_idx'),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['created_at'], name='api_checkou_created_bfe441_idx'),
        ),
        migrations.AddIndex(
            model_name='counterrefundrequest',
            index=models.Index(fields=['refund_id', 'status'], name='api_counter_refund__c3b264_idx'),
        ),
        migrations.AddIndex(
            model_name='counterrefundrequest',
            index=models.Index(fields=['seller_id', 'requested_at'], name='api_counter_seller__86d3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['current_product_count', 'product_limit'], name='api_custome_current_3ef6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['customer', 'created_at'], name='api_custome_custome_1cd373_idx'),
        ),
        migrations.AddIndex(
            model_name='customeractivity',
            index=models.Index(fields=['product', 'created_at'], name='api_custome_product_cfe32d_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order', 'status'], name='api_deliver_order_i_e86cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['rider', 'status'], name='api_deliver_rider_i_a81014_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'scheduled_delivery_time'], name='api_deliver_status_48c0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['created_at'], name='api_deliver_created_5fe707_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['delivered_at'], name='api_deliver_deliver_afb191_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['dispute_id'], name='api_dispute_dispute_f8306b_idx'),
        ),
        migrations.AddIndex(
            model_name='disputerequest',
            index=models.Index(fields=['refund_id', 'status'], name='api_dispute_refund__8dcbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='disputerequest',
            index=models.Index(fields=['requested_by', 'created_at'], name='api_dispute_request_0a36a0_idx'),
        ),
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['customer', 'product'], name='api_favorit_custome_8ff48b_idx'),
        ),
        migrations.AddIndex(
            model_name='issues',
            index=models.Index(fields=['product'], name='api_issues_product_1d10cb_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['user', 'timestamp'], name='api_logs_user_id_2a15a5_idx'),
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['timestamp'], name='api_logs_timesta_a73708_idx'),
        ),
        migrations.AddIndex(
            model_name='moderator',
            index=models.Index(fields=['approval_status'], name='api_moderat_approva_4ff0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='api_notific_user_id_537f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='api_notific_created_238c70_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='api_order_user_id_d6ac48_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='api_order_status_1d49fe_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['approval', 'status'], name='api_order_approva_8c1d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='api_order_created_7fb22c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['total_amount'], name='api_order_total_a_cf727a_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expired_at'], name='api_otp_expired_d1784b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='api_payment_order_i_e43f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'transaction_date'], name='api_payment_status_d3f8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_date'], name='api_payment_transac_230ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'upload_status'], name='api_product_shop_id_f8f170_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['customer', 'upload_status'], name='api_product_custome_c66e70_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['upload_status', 'created_at'], name='api_product_upload__955fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'upload_status'], name='api_product_categor_a32a57_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='api_product_price_b6b1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='api_product_created_a91d70_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_removed', 'removed_at'], name='api_product_is_remo_e56dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='productmedia',
            index=models.Index(fields=['product'], name='api_product_product_10420e_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['product', 'is_active'], name='api_product_product_d904a2_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['sku_code'], name='api_product_sku_cod_b2a56d_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['quantity', 'is_active'], name='api_product_quantit_06230d_idx'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['price'], name='api_product_price_f5f979_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['order_id', 'status'], name='api_refund_order_i_b2e7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['requested_by', 'status'], name='api_refund_request_503960_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'requested_at'], name='api_refund_status_cd8289_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_payment_status'], name='api_refund_refund__c6f6af_idx'),
        ),
        migrations.AddIndex(
            model_name='refundmedia',
            index=models.Index(fields=['refund_id'], name='api_refundm_refund__e9af6c_idx'),
        ),
        migrations.AddIndex(
            model_name='refundproof',
            index=models.Index(fields=['refund'], name='api_refundp_refund__f7df5a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='api_report_report__7e7523_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='api_report_status_2ddde8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_moderator', 'status'], name='api_report_assigne_7f3075_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_account', 'status'], name='api_report_reporte_e59198_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_product', 'status'], name='api_report_reporte_425512_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_shop', 'status'], name='api_report_reporte_241505_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['report', 'created_at'], name='api_reportc_report__f8298e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomment',
            index=models.Index(fields=['user', 'created_at'], name='api_reportc_user_id_ad17ac_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmedia',
            index=models.Index(fields=['report'], name='api_reportm_report__789c65_idx'),
        ),
        migrations.AddIndex(
            model_name='returnaddress',
            index=models.Index(fields=['shop', 'seller'], name='api_returna_shop_id_fc2131_idx'),
        ),
        migrations.AddIndex(
            model_name='returnaddress',
            index=models.Index(fields=['refund'], name='api_returna_refund__df23e6_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['refund_id', 'status'], name='api_returnr_refund__b14e92_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestitem',
            index=models.Index(fields=['status', 'return_deadline'], name='api_returnr_status_50d51e_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequestmedia',
            index=models.Index(fields=['return_id'], name='api_returnr_return__5cf0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop', 'rating'], name='api_review_shop_id_c2d6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'rating'], name='api_review_product_3b36e6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['customer', 'created_at'], name='api_review_custome_b847e6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='api_review_created_24e07e_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['verified', 'availability_status'], name='api_rider_verifie_ecd891_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['availability_status', 'is_accepting_deliveries'], name='api_rider_availab_eb0625_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['last_status_update'], name='api_rider_last_st_17f9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='riderschedule',
            index=models.Index(fields=['rider', 'day_of_week'], name='api_ridersc_rider_i_78958a_idx'),
        ),
        migrations.AddIndex(
            model_name='riderschedule',
            index=models.Index(fields=['day_of_week', 'is_available'], name='api_ridersc_day_of__37f42b_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default'], name='api_shippin_user_id_bb003b_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_active'], name='api_shippin_user_id_19c8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['city', 'province'], name='api_shippin_city_cf2f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['customer', 'verified'], name='api_shop_custome_6f4c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['verified', 'status'], name='api_shop_verifie_965ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['name'], name='api_shop_name_819709_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['created_at'], name='api_shop_created_311fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_suspended', 'suspended_until'], name='api_shop_is_susp_df0674_idx'),
        ),
        migrations.AddIndex(
            model_name='shopfollow',
            index=models.Index(fields=['shop', 'followed_at'], name='api_shopfol_shop_id_c8a37c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopfollow',
            index=models.Index(fields=['customer', 'followed_at'], name='api_shopfol_custome_3cc2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['rider', 'start_date'], name='api_timeoff_rider_i_268d02_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['status', 'start_date'], name='api_timeoff_status_425afd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='api_user_usernam_edfd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='api_user_email_a7eefd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='api_user_created_f8e07b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_suspended', 'suspended_until'], name='api_user_is_susp_25ec79_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_customer', 'is_suspended'], name='api_user_is_cust_153cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_moderator', 'is_suspended'], name='api_user_is_mode_da5c58_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_rider', 'is_suspended'], name='api_user_is_ride_b8d150_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='api_userpay_user_id_b934c2_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['method_type', 'user'], name='api_userpay_method__81c359_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoptions',
            index=models.Index(fields=['variant'], name='api_variant_variant_29fb50_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoptions',
            index=models.Index(fields=['created_at'], name='api_variant_created_97d8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product'], name='api_variant_product_386403_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code', 'is_active'], name='api_voucher_code_22be1d_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['shop', 'is_active', 'valid_until'], name='api_voucher_shop_id_fc7fba_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['valid_until', 'is_active'], name='api_voucher_valid_u_0d8ac4_idx'),
        ),
    ]
