# Generated by Django 5.2.7 on 2025-10-27 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.OneToOneField(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
            ],
        ),
    ]
