# Generated by Django 5.2.7 on 2026-01-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipt/'),
        ),
    ]
