# Generated by Django 6.0 on 2025-12-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequestitem',
            name='logistic_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
