# Generated by Django 5.2.7 on 2026-02-08 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('delivery', 'Delivery'), ('seller', 'Seller'), ('pickup', 'Pickup')], max_length=20)),
                ('file_data', models.FileField(upload_to='delivery/proofs/')),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.delivery')),
            ],
            options={
                'indexes': [models.Index(fields=['delivery', 'uploaded_at'], name='api_proof_deliver_8ed0f6_idx'), models.Index(fields=['uploaded_at'], name='api_proof_uploade_99afba_idx')],
            },
        ),
    ]
