# Generated by Django 5.2.7 on 2026-01-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='refund_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsku',
            name='refund_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
