# Generated by Django 5.2.7 on 2026-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_approval',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
