# Generated by Django 5.2.7 on 2026-02-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='reject_reason_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='reject_reason_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
