# Generated by Django 6.0 on 2025-12-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_returnrequestitem_logistic_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
