# Generated by Django 6.0 on 2026-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20260116_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
    ]
