# Generated by Django 5.2.7 on 2026-01-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_admin_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='admin_approval',
            new_name='approval',
        ),
    ]
