# Generated by Django 6.0 on 2025-12-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_refund_refund_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequestitem',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('received', 'Received'), ('inspected', 'Inspected'), ('completed', 'Completed'), ('problem', 'Problem')], default='pending', max_length=20),
        ),
    ]
