# Generated by Django 5.2.7 on 2025-10-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logs_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_stage',
            field=models.IntegerField(default=0),
        ),
    ]
