# Generated by Django 5.2.7 on 2026-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refund_reject_reason_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
