# Generated by Django 5.2.7 on 2026-01-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_airecommendation_api_airecom_custome_ad1273_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='api.productsku'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'user', 'sku')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['sku', 'is_ordered'], name='api_cartite_sku_id_e60f89_idx'),
        ),
    ]
