# Generated by Django 6.0 on 2026-01-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20260116_1335'),
        ('api', '0004_rename_admin_approval_order_approval'),
    ]

    operations = [
    ]
