# Generated by Django 6.0 on 2026-01-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_is_refundable_productsku_is_refundable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='refund_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsku',
            name='refund_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
