# Generated by Django 6.0 on 2025-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_returnrequestitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequestitem',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('received', 'Received'), ('inspected', 'Inspected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('problem', 'Problem')], default='pending', max_length=20),
        ),
    ]
