# Generated by Django 5.2.7 on 2026-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delivery_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price of the product when new', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='How long the product has been used', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_unit',
            field=models.CharField(choices=[('months', 'Months'), ('years', 'Years')], default='months', help_text='Unit of measurement for usage time', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Like New', 'Like New'), ('New', 'New'), ('Refurbished', 'Refurbished'), ('Used - Excellent', 'Used - Excellent'), ('Used - Good', 'Used - Good')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['original_price'], name='api_product_origina_a7d1b4_idx'),
        ),
    ]
