# Generated by Django 5.2.7 on 2026-02-13 13:39

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_original_price_product_usage_time_and_more'),
    ]

    operations = [
        # First, remove the old index and constraints that depend on old fields
        migrations.RemoveIndex(
            model_name='cartitem',
            name='api_cartite_sku_id_e60f89_idx',
        ),
        
        # Remove the old unique_together constraint (without variant field)
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        
        # Remove the old sku field from cartitem (must be done before removing ProductSKU)
        migrations.RemoveField(
            model_name='cartitem',
            name='sku',
        ),
        
        # Now remove the old ProductSKU and VariantOptions models
        migrations.RemoveField(
            model_name='productsku',
            name='accepted_categories',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductSKU',
        ),
        
        migrations.RemoveField(
            model_name='variantoptions',
            name='variant',
        ),
        migrations.DeleteModel(
            name='VariantOptions',
        ),
        
        # Add the new variant field to cartitem
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='api.variants'),
        ),
        
        # Now add all the new fields to Variants
        migrations.AddField(
            model_name='variants',
            name='allow_swap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variants',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 13, 13, 39, 21, 175365, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variants',
            name='critical_trigger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/variants/'),
        ),
        migrations.AddField(
            model_name='variants',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='is_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variants',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='maximum_additional_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AddField(
            model_name='variants',
            name='minimum_additional_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AddField(
            model_name='variants',
            name='option_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='option_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='option_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='option_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variants',
            name='refund_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variants',
            name='sku_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='swap_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='swap_type',
            field=models.CharField(choices=[('direct_swap', 'Direct swap'), ('swap_plus_payment', 'Swap + payment')], default='direct_swap', max_length=30),
        ),
        migrations.AddField(
            model_name='variants',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='weight_unit',
            field=models.CharField(blank=True, default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='variants',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='api.product'),
        ),
        
        # Now set the new unique_together constraint (variant field exists now)
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'user', 'variant')},
        ),
        
        # Add the new indexes
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['variant', 'is_ordered'], name='api_cartite_variant_15dcec_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'is_active'], name='api_variant_product_3b1326_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['sku_code'], name='api_variant_sku_cod_a820bb_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['quantity', 'is_active'], name='api_variant_quantit_dfd878_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['price'], name='api_variant_price_19416d_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['created_at'], name='api_variant_created_1e305b_idx'),
        ),
    ]