# Generated by Django 6.0 on 2026-01-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_completed_at_product_refund_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_refundable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
