# Generated by Django 6.0 on 2025-12-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_refund_status_returnaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnaddress',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_return_addresses', to='api.user'),
        ),
        migrations.AddField(
            model_name='returnaddress',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_addresses', to='api.shop'),
        ),
    ]
