# Generated by Django 5.2.7 on 2025-11-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_riders', to='api.user'),
        ),
        migrations.AddField(
            model_name='rider',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/licenses/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rider',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='riders/vehicles/'),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rider',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rider',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
