# Generated by Django 5.2.7 on 2026-02-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_fee',
        ),
    ]
