# Generated by Django 6.0 on 2025-12-28 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_returnaddress_seller_returnaddress_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnaddress',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_address', to='api.refund'),
        ),
    ]
