# Generated by Django 5.2.7 on 2026-02-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_delivery_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='depreciation_rate',
            field=models.FloatField(blank=True, help_text='Annual depreciation rate percentage', null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price of the item when new', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='usage_period',
            field=models.FloatField(blank=True, help_text='How long the item has been used', null=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='usage_unit',
            field=models.CharField(blank=True, choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], help_text='Unit of measurement for usage period', max_length=10, null=True),
        ),
    ]
