# Generated by Django 6.0 on 2025-12-28 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_returnaddress_refund'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=50)),
                ('file_data', models.FileField(upload_to='refunds/proof/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.refund')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_refund_proofs', to='api.user')),
            ],
        ),
    ]
