# Generated by Django 5.2.7 on 2025-11-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_stage',
            field=models.IntegerField(),
        ),
    ]
