# Generated by Django 5.2.7 on 2026-02-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_variants_depreciation_rate_variants_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_price_b6b1d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_origina_a7d1b4_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='compare_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='critical_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usage_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='usage_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='height',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='length',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='width',
        ),
        migrations.AddField(
            model_name='variants',
            name='critical_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
