# Generated by Django 6.0 on 2025-12-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_refundproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approved_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='total_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
