# Generated by Django 5.2.7 on 2025-11-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_registration_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
