# Generated by Django 5.2.7 on 2026-02-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_api_product_price_b6b1d7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
