# Generated by Django 6.0 on 2025-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_refund_approved_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterrefundrequest',
            name='counter_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
