# Generated by Django 5.2.7 on 2026-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
