# Generated by assistant to add counter_refund_type to CounterRefundRequest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_counterrefundrequest_counter_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterrefundrequest',
            name='counter_refund_type',
            field=models.CharField(blank=True, max_length=10, null=True, choices=[('return', 'Return'), ('keep', 'Keep')]),
        ),
    ]
