# Generated by Django 5.2.7 on 2025-11-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_boostplan_refundpolicy_category_product_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.product'),
        ),
    ]
