# Generated by Django 5.2.7 on 2026-02-26 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delivery_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('GCash', 'GCash'), ('Maya', 'Maya'), ('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boost',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boost',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_boost_payments', to='api.user'),
        ),
        migrations.AddField(
            model_name='boost',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text='Payment receipt image for boost', null=True, upload_to='boost/receipts/'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('payment_pending', 'Payment Pending')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='boost',
            index=models.Index(fields=['payment_verified', 'status'], name='api_boost_payment_1dbd47_idx'),
        ),
    ]
