# Generated by Django 5.2.7 on 2026-02-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_boost_payment_method_boost_payment_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputerequest',
            name='case_category',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='refund_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
