# Generated by Django 6.0 on 2026-01-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_appliedgift_appliedgiftproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedgift',
            name='minimum_spend',
        ),
    ]
