# Generated by Django 5.2.7 on 2025-11-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_review_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
