# Generated by Django 5.2.7 on 2026-01-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delivery_actual_minutes_delivery_delivery_rating_and_more'),
        ('api', '0014_remove_appliedgift_minimum_spend'),
    ]

    operations = [
    ]
