# Generated by Django 5.2.7 on 2025-11-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_shop_status_shop_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
