# Generated by Django 5.2.7 on 2026-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delivery_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='availability_status',
            field=models.CharField(choices=[('offline', 'Offline'), ('available', 'Available for Deliveries'), ('busy', 'Busy - On Delivery'), ('break', 'On Break'), ('unavailable', 'Temporarily Unavailable')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_accepting_deliveries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_status_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
