# Generated by Django 5.2.7 on 2026-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userpaymentdetail_userwallet_wallettransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='failed_deliveries_count',
            field=models.IntegerField(default=0),
        ),
    ]
