# Generated by Django 5.2.7 on 2026-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rider_failed_deliveries_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='declined_order_count',
            field=models.IntegerField(default=0),
        ),
    ]
