# Generated by Django 5.2.7 on 2025-11-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_customer_id_airecommendation_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='moderator',
            old_name='user',
            new_name='moderator',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='user',
            new_name='rider',
        ),
    ]
