# Generated by Django 5.2.7 on 2026-03-13 02:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rider_declined_order_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='api_review_shop_id_c2d6cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='api_review_product_3b36e6_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='accuracy_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='average_rating',
            field=models.FloatField(blank=True, help_text='Average of condition, accuracy, value, and delivery ratings', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='condition_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='delivery_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.rider'),
        ),
        migrations.AddField(
            model_name='review',
            name='value_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop', 'average_rating'], name='api_review_shop_id_2c6bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'average_rating'], name='api_review_product_0b896d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rider', 'average_rating'], name='api_review_rider_i_f0f653_idx'),
        ),
    ]
