# Generated by Django 5.2.7 on 2025-11-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_user_admin_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to='api.user'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
