# Generated by Django 5.2.7 on 2026-03-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_wallettransaction_order_wallettransaction_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='product/variants/proof/'),
        ),
    ]
