# Generated by Django 5.2.7 on 2026-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_variants_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
