# Generated by Django 6.0 on 2026-03-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_variants_proof_image'),
        ('api', '0022_merge_20260315_2045'),
    ]

    operations = [
    ]
