# Generated by Django 5.2.7 on 2025-11-26 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delivery_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_products', to='api.category'),
        ),
    ]
