# Generated by Django 5.2.7 on 2026-03-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_order_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
