# Generated by Django 5.2.7 on 2025-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_product_category_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='minimum_spend',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
