# Generated by Django 5.2.7 on 2026-03-16 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delivery_metadata_alter_order_pickup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderRemittance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('Maya', 'Maya'), ('GCash', 'GCash'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], default='Maya', max_length=50)),
                ('maya_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_remittances', to='api.user')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='api.rider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderRemittanceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_remitted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_cod', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_items', to='api.delivery')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.riderremittance')),
            ],
        ),
        migrations.AddIndex(
            model_name='riderremittance',
            index=models.Index(fields=['rider', 'status'], name='api_riderre_rider_i_8a84a7_idx'),
        ),
        migrations.AddIndex(
            model_name='riderremittance',
            index=models.Index(fields=['reference_number'], name='api_riderre_referen_cedd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='riderremittance',
            index=models.Index(fields=['status', 'created_at'], name='api_riderre_status_c5c66f_idx'),
        ),
        migrations.AddIndex(
            model_name='riderremittanceitem',
            index=models.Index(fields=['remittance'], name='api_riderre_remitta_e1d479_idx'),
        ),
        migrations.AddIndex(
            model_name='riderremittanceitem',
            index=models.Index(fields=['delivery'], name='api_riderre_deliver_7aaebb_idx'),
        ),
    ]
