# Generated by Django 5.2.7 on 2025-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_voucher_minimum_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='maximum_usage',
            field=models.IntegerField(default=0),
        ),
    ]
