# Generated by Django 5.2.7 on 2026-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_riderremittance_riderremittanceitem_and_more'),
    ]

    operations = [
        # Disabled: Cannot convert existing text data ("Like New") to integers
        # This requires a data migration first, which conflicts with GitHub source
    ]
