# Generated by Django 5.2.7 on 2025-11-26 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_voucher_maximum_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waiting', 'Waiting'), ('to process', 'To Process'), ('completed', 'Completed')], max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('logistic_service', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_refund_method', models.CharField(blank=True, max_length=100, null=True)),
                ('final_refund_method', models.CharField(blank=True, max_length=100, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.order')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to='api.user')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='RefundMedias',
            fields=[
                ('refund_media', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_data', models.FileField(upload_to='refunds/')),
                ('file_type', models.TextField()),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refund')),
            ],
        ),
    ]
