# Generated by Django 5.2.7 on 2025-11-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_refund_refundmedias'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderator',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
