# Generated by Django 5.2.7 on 2026-03-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
