# Generated by Django 5.2.7 on 2026-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_variants_height_variants_length_variants_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='dimension_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
