# Generated by Django 5.2.7 on 2025-12-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_product_is_removed_product_removal_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
