# Generated by Django 5.2.7 on 2025-12-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_product_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='critical_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
