# Generated by Django 5.2.7 on 2026-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_variants_dimension_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user/profile_pictures/'),
        ),
    ]
