# Generated by Django 5.2.7 on 2025-12-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_product_critical_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enable_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
