# Generated by Django 5.2.7 on 2026-03-19 01:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='voucher',
            name='api_voucher_shop_id_fc7fba_idx',
        ),
        migrations.RemoveIndex(
            model_name='voucher',
            name='api_voucher_valid_u_0d8ac4_idx',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='voucher',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['shop', 'is_active'], name='api_voucher_shop_id_6855b1_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['start_date', 'end_date'], name='api_voucher_start_d_3c724f_idx'),
        ),
    ]
