# Generated by Django 5.2.7 on 2025-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_product_enable_pickup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='enable_pickup',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
