# Generated by Django 5.2.7 on 2026-03-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_voucher_api_voucher_shop_id_fc7fba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(blank=True, choices=[('shop', 'Shop Voucher'), ('product', 'Product Voucher')], max_length=20, null=True),
        ),
    ]
