# Generated by Django 5.2.7 on 2026-03-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_voucher_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='payment_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='api.userpaymentdetail'),
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='api.checkout')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.refund')),
            ],
            options={
                'unique_together': {('refund', 'checkout')},
            },
        ),
    ]
