# Generated by Django 5.2.7 on 2025-12-08 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_product_enable_pickup_order_delivery_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoostPlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('boost_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.boostplan')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boostfeature')),
            ],
            options={
                'unique_together': {('boost_plan', 'feature')},
            },
        ),
    ]
