# Generated by Django 5.2.7 on 2026-03-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_refund_payment_detail_refunditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputerequest',
            name='refund_fee',
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
