# Generated by Django 5.2.7 on 2025-12-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_boostfeature_boostplanfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boostfeature',
            name='icon',
        ),
    ]
