# Generated by Django 5.2.7 on 2025-12-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_boostfeature_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='used_for',
        ),
    ]
