# Generated by Django 5.2.7 on 2026-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_disputerequest_refund_fee_refund_refund_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunditem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='refunditem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
