# Generated by Django 5.2.7 on 2026-03-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_refunditem_amount_refunditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
