# Generated by Django 5.2.7 on 2025-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_product_used_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_limit',
            field=models.IntegerField(default=500),
        ),
    ]
