# Generated by Django 5.2.7 on 2026-03-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='direct_product_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='direct_product_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='direct_product_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='direct_product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='direct_shop_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='direct_shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='direct_variant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
