# Generated by Django 6.0 on 2025-12-15 08:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_customer_product_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accepted_categories',
            field=models.ManyToManyField(blank=True, related_name='accepted_for_swaps', to='api.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='maximum_additional_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_additional_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='open_for_swap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='swap_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='swap_type',
            field=models.CharField(choices=[('direct_swap', 'Direct swap'), ('swap_plus_payment', 'Swap + payment')], default='direct_swap', max_length=30),
        ),
    ]
