# Generated by Django 5.2.7 on 2026-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_checkout_direct_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='business_permit_image',
            field=models.ImageField(blank=True, help_text='Upload of business permit', null=True, upload_to='shop/legal/permits/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_permit_number',
            field=models.CharField(blank=True, help_text='Local government business permit number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_registration_image',
            field=models.ImageField(blank=True, help_text='Upload of DTI or SEC certificate', null=True, upload_to='shop/legal/registration/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='DTI or SEC registration number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_registration_type',
            field=models.CharField(blank=True, choices=[('DTI', 'DTI'), ('SEC', 'SEC')], help_text='Type of business registration', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='government_id_image_back',
            field=models.ImageField(blank=True, help_text='Back of government ID', null=True, upload_to='shop/legal/government_id/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='government_id_image_front',
            field=models.ImageField(blank=True, help_text='Front of government ID', null=True, upload_to='shop/legal/government_id/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='government_id_number',
            field=models.CharField(blank=True, help_text='Government ID number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='government_id_type',
            field=models.CharField(blank=True, help_text="Type of government ID (e.g. PhilSys, Passport, Driver's License)", max_length=50, null=True),
        ),
    ]
