# Generated by Django 5.2.7 on 2026-03-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_shop_business_permit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('return', 'Return Item'), ('keep', 'Keep Item'), ('replace', 'Replacement Item')], max_length=10),
        ),
    ]
