# Generated by Django 5.2.7 on 2026-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_refund_refund_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundmedia',
            name='uploaded_by_entity',
            field=models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('rider', 'Rider')], max_length=10, null=True),
        ),
    ]
