# Generated by Django 6.0 on 2025-12-16 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_order_delivery_address_and_more'),
        ('api', '0039_add_productsku'),
        ('api', '0040_product_height_product_length_product_weight_and_more'),
    ]

    operations = [
    ]
