# Generated by Django 5.2.7 on 2026-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_refundmedia_uploaded_by_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
