# Generated by Django 6.0 on 2025-12-16 06:49

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_merge_20251216_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='maximum_additional_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='minimum_additional_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='swap_type',
            field=models.CharField(choices=[('direct_swap', 'Direct swap'), ('swap_plus_payment', 'Swap + payment')], default='direct_swap', max_length=30),
        ),
    ]
