# Generated by Django 6.0 on 2025-12-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_cleanup_models'),
        ('api', '0042_alter_productsku_id_and_more'),
    ]

    operations = [
    ]
