# Generated by Django 5.2.7 on 2025-12-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_merge_20251216_1502'),
        ('api', '0044_remove_variantoptions_image'),
    ]

    operations = [
    ]
