# Generated by Django 5.2.7 on 2026-04-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='disputerequest',
            name='api_dispute_request_0a36a0_idx',
        ),
        migrations.RemoveField(
            model_name='disputerequest',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='adjusted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_disputes', to='api.user'),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='liability',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='outcome',
            field=models.CharField(blank=True, choices=[('favor_buyer', 'Favor Buyer'), ('favor_seller', 'Favor Seller'), ('favor_rider', 'Favor Rider'), ('partial_resolution', 'Partial Resolution')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='requested_by_entity',
            field=models.CharField(default='buyer', max_length=10),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_disputes', to='api.user'),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='rider_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_disputes', to='api.user'),
        ),
        migrations.AddField(
            model_name='disputerequest',
            name='seller_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='disputerequest',
            name='case_category',
            field=models.CharField(blank=True, choices=[('merchant_fulfillment_issue', 'Merchant Fulfillment Issue'), ('logistics_delivery_issue', 'Logistics/Delivery Issue'), ('customer_related_issue', 'Customer Related Issue'), ('shared_responsibility', 'Shared Responsibility'), ('platform_system_issue', 'Platform System Issue')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='disputerequest',
            index=models.Index(fields=['requested_by_entity', 'created_at'], name='api_dispute_request_4e974c_idx'),
        ),
    ]
