# Generated by Django 5.2.7 on 2026-04-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_disputerequest_api_dispute_request_0a36a0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
