# Generated by Django 5.2.7 on 2025-12-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_merge_20251216_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
