# Generated by Django 6.0 on 2025-12-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_merge_20251216_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('negotiation', 'Negotiation'), ('approved', 'Approved'), ('waiting', 'Waiting For Return'), ('to_verify', 'To Verify'), ('to_process', 'To Process'), ('dispute', 'Dispute'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='variantoptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
