# Generated by Django 6.0 on 2025-12-17 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_refund_payment_status_alter_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='admin_decision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='dispute_filed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='dispute_filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='refund',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='negotiation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='request_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='seller_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='seller_suggested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='seller_suggested_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='seller_suggested_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='total_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
