# Generated by Django 5.2.7 on 2026-04-11 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_shippingaddress_latitude_shippingaddress_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_data', models.FileField(upload_to='reviews/media/')),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.review')),
            ],
            options={
                'indexes': [models.Index(fields=['review'], name='api_reviewm_review__6430f5_idx'), models.Index(fields=['uploaded_at'], name='api_reviewm_uploade_dd1148_idx')],
            },
        ),
    ]
