# Generated by Django 6.0 on 2025-12-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_cartitem_is_ordered_alter_variantoptions_created_at'),
        ('api', '0047_refund_admin_decision_refund_admin_response_and_more'),
    ]

    operations = [
    ]
