# Generated by Django 5.2.7 on 2026-04-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_reviewmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='failed_reason',
            field=models.CharField(blank=True, choices=[('customer_unreachable', 'Customer Unreachable'), ('return_to_seller', 'Return to Seller')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_offer', 'Pending Offer'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
