# Generated by Django 6.0 on 2025-12-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_add_approved_return_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_category',
            field=models.CharField(choices=[('return_item', 'Return Item'), ('keep_item', 'Keep Item'), ('replacement', 'Replacement')], default='return_item', max_length=20),
        ),
    ]
