# Generated by Django 5.2.7 on 2026-04-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.variants'),
        ),
    ]
