# Generated by Django 6.0 on 2025-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_refund_refund_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='buyer_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
