# Generated by Django 6.0 on 2025-12-17 19:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_refund_buyer_notified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnWaybill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_contact_number', models.CharField(blank=True, default='', max_length=20)),
                ('shop_address', models.TextField()),
                ('waybill_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('logistic_service', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('return_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waybill', to='api.refund')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_waybills', to='api.shop')),
            ],
            options={
                'verbose_name': 'Return Waybill',
                'verbose_name_plural': 'Return Waybills',
                'ordering': ['-created_at'],
            },
        ),
    ]
