# Generated by Django 5.2.7 on 2026-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_checkout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='value_added_tax',
            field=models.FloatField(default=0),
        ),
    ]
