# Generated by Django 6.0 on 2025-12-17 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_create_return_waybill'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('item_not_received', 'Item Not Received'), ('item_damaged', 'Item Damaged'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not As Described'), ('seller_unresponsive', 'Seller Unresponsive'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='filed', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('buyer_wins', 'Buyer Wins'), ('seller_wins', 'Seller Wins'), ('partial_refund', 'Partial Refund'), ('dismissed', 'Dismissed'), ('withdrawn', 'Withdrawn')], max_length=30, null=True)),
                ('awarded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('filed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.user')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('refund', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.refund')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='disputes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.disputerequest')),
            ],
        ),
    ]
