# Generated by Django 5.2.7 on 2026-04-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='value_added_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
