# Generated by Django 5.2.7 on 2026-04-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_variants_value_added_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='value_added_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
