# Generated by Django 5.2.7 on 2026-04-22 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_variants_value_added_tax_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoucherUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to='api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_usages', to='api.user')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usages', to='api.voucher')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'voucher'], name='api_uservou_user_id_794514_idx'), models.Index(fields=['used_at'], name='api_uservou_used_at_dc1e59_idx'), models.Index(fields=['order'], name='api_uservou_order_i_50839a_idx')],
                'unique_together': {('user', 'voucher')},
            },
        ),
    ]
