# Generated by Django 5.2.7 on 2026-04-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_uservoucherusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
