# Generated by Django 5.2.7 on 2026-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_order_shipping_fee_order_transaction_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_type',
            field=models.CharField(choices=[('order', 'Order Delivery'), ('return', 'Return Pickup'), ('replacement', 'Replacement')], default='order', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnrequestitem',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('received', 'Received'), ('inspected', 'Inspected'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('problem', 'Problem'), ('pickup_requested', 'Pickup Requested'), ('pickup_accepted', 'Pickup Accepted'), ('pickup_rejected', 'Pickup Rejected')], default='pending', max_length=20),
        ),
    ]
