# Generated by Django 5.2.7 on 2026-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_delivery_delivery_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.AddField(
            model_name='checkout',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fees_breakdown',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['direct_shop_id'], name='api_checkou_direct__ff6bf6_idx'),
        ),
    ]
