# Generated by Django 5.2.7 on 2026-04-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_order_shipping_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source_type',
            field=models.CharField(choices=[('personal_sale', 'Personal Sale'), ('shop_sale', 'Shop Sale'), ('refund', 'Refund'), ('dispute', 'Dispute'), ('withdrawal', 'Withdrawal'), ('delivery_fee', 'Delivery Fee'), ('cod_collection', 'COD Collection')], max_length=20),
        ),
    ]
