# Generated by Django 5.2.7 on 2026-04-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_wallettransaction_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_statuses', to='api.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='api.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'shop'], name='api_ordersh_order_i_2bda53_idx'), models.Index(fields=['status'], name='api_ordersh_status_bdec2f_idx')],
                'unique_together': {('order', 'shop')},
            },
        ),
    ]
