# Generated by Django 5.2.7 on 2026-04-29 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_ordershopstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershopstatus',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # REMOVE THIS SECTION - it's causing the error
        # migrations.AlterField(
        #     model_name='ordershopstatus',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        # ),
        migrations.AlterField(
            model_name='ordershopstatus',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to='api.shop'),
        ),
        migrations.AlterField(
            model_name='ordershopstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AddIndex(
            model_name='ordershopstatus',
            index=models.Index(fields=['order', 'shop'], name='api_ordersh_order_i_2bda53_idx'),
        ),
        migrations.AddIndex(
            model_name='ordershopstatus',
            index=models.Index(fields=['status'], name='api_ordersh_status_bdec2f_idx'),
        ),
    ]