# Generated by Django 5.2.7 on 2026-04-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_ordershopstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.shop'),
        ),
    ]
