# Generated by Django 5.2.7 on 2026-05-01 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_delivery_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
    ]
