# Generated by Django 5.2.7 on 2026-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_refund_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='transaction_fee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ordershopstatus',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordershopstatus',
            name='pickup_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordershopstatus',
            name='refund_expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
