# Generated by Django 5.2.7 on 2026-05-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_checkout_transaction_fee_ordershopstatus_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
