# Generated by Django 5.2.7 on 2026-05-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_checkout_discount_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='capped_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
