# Generated by Django 5.2.7 on 2026-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_voucher_capped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershopstatus',
            name='refund_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
