# Generated by Django 5.2.7 on 2026-05-06 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_ordershopstatus_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCompensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compensation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='shop/compensation/receipts/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='api.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_compensations', to='api.user')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='api.shop')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.voucher')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'status'], name='api_shopcom_shop_id_3c2272_idx'), models.Index(fields=['order'], name='api_shopcom_order_i_7823f7_idx')],
                'unique_together': {('order', 'shop')},
            },
        ),
    ]
