name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build ./crimsotech_django -t pajiimarr/crimsotech_django:latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u pajiimarr --password-stdin

      - name: Push Docker image
        run: docker push pajiimarr/crimsotech_django:latest
      
      - name: Force rebuild on Digital Ocean App Platform
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.DIGITAL_OCEAN_TOKEN }}" \
            -d '{"force_build": true}' \
            "https://api.digitalocean.com/v2/apps/${{ secrets.DIGITAL_OCEAN_APP_ID }}/deployments"